version: '0.2.0'

# Language settings
language:
  chat: "en"   # Chat output language (en, ko)

# Particle settings
particles:
  # Particle type, height, count
  - type: "HAPPY_VILLAGER"
    height: 20
    count: 10
  - type: "ENCHANT"
    height: 20
    count: 10
  - type: "END_ROD"
    height: 20
    count: 5
  - type: "DRAGON_BREATH"
    height: 20
    count: 5

# Particle duration (seconds)
particle-duration: 30

# Particle spawn interval (seconds)
particle-interval: 1

# Particle effect settings
particle-effects:
  show-pillar: true    # Show particle pillar at villager location
  show-line: true      # Show particle line between player and villager
  line-points: 20      # Number of points in the particle line
  line-update-interval: 0.1  # Line update interval in seconds (0.1 = 5 ticks)