# Language settings
language:
  chat: "en"   # Chat output language (en, ko)

# Particle settings
particles:
  # Particle type, height, count
  - type: "HAPPY_VILLAGER"
    height: 10
    count: 10
  - type: "ENCHANT"
    height: 10
    count: 10
  - type: "END_ROD"
    height: 10
    count: 5
  - type: "DRAGON_BREATH"
    height: 10
    count: 5

# Particle duration (seconds)
particle-duration: 30

# Particle spawn interval (seconds)
particle-interval: 1