name: VillagerEnchantTracker
version: '0.2.0'
main: org.teamck.villagerEnchantTracker.VillagerEnchantTracker
api-version: '1.21'
softdepend: [WorldEdit, FastAsyncWorldEdit]
commands:
  librariandb:
    description: Manage librarian villager trades
    usage: /<command> [create|search|list|delete|edit-description|particle]
    permission: villagerenchanttracker.admin
  findvillager:
    description: Find nearby villagers with specific enchantments
    usage: /<command> <enchantment>
    permission: villagerenchanttracker.use
  villagerregion:
    description: Manage regions for villager trade tracking
    usage: /<command> [create|list|delete]
    permission: villagerenchanttracker.admin