name: VillagerEnchantTracker
version: 0.1.0
main: org.teamck.villagerEnchantTracker.VillagerEnchantTracker
api-version: '1.21'
commands:
  librariandb:
    description: Villager Enchant Tracker management command
    usage: /<command> [create|search|list|delete|edit-description|particle]
  findvillager:
    description: Search for nearby villager trades
    usage: /<command> <enchantment name or id> [particle]
permissions:
  villagerenchanttracker.admin:
    description: Allows managing Villager Enchant Tracker
    default: op
  villagerenchanttracker.find:
    description: Allows searching for nearby villager trades
    default: true