name: VillagerEnchantTracker
version: '0.3.0'
main: org.teamck.villagerEnchantTracker.core.VillagerEnchantTracker
api-version: '1.21'
softdepend: [WorldEdit, FastAsyncWorldEdit]
commands:
  findvillager:
    description: Find nearby villagers with specific enchantments and mark them with particles
    usage: /<command> <enchantment>
    permission: villagerenchanttracker.use
  vet:
    description: Main command for VillagerEnchantTracker
    usage: |
      §6=== VillagerEnchantTracker Commands ===
      §e/vet trade [create|search|list|delete|edit-description]
      §e/vet region [create|list|delete|edit]
      §e/vet evt [nearby|region]
    permission: villagerenchanttracker.use
    aliases: [villagerenchanttracker]

permissions:
  villagerenchanttracker.use:
    description: Allows use of read-only features (search, list, etc)
    default: true
  villagerenchanttracker.write:
    description: Allows use of write features (create, delete, edit, etc)
    default: op
    children:
      villagerenchanttracker.use: true