name: VillagerEnchantTracker
version: '0.2.0'
main: org.teamck.villagerEnchantTracker.core.VillagerEnchantTracker
api-version: '1.21'
softdepend: [WorldEdit, FastAsyncWorldEdit]
commands:
  librariandb:
    description: Manage librarian villager trades
    usage: /<command> [create|search|list|delete|edit-description|particle]
    permission: villagerenchanttracker.admin
  findvillager:
    description: Find nearby villagers with specific enchantments
    usage: /<command> <enchantment>
    permission: villagerenchanttracker.use
  villagerregion:
    description: Manage regions for villager trade tracking
    usage: /<command> [create|list|delete]
    permission: villagerenchanttracker.admin
  evtintegration:
    description: Integration commands for EasyVillagerTrade mod
    usage: |
      §6=== EVT Integration Commands ===
      §e/evtintegration nearby [radius] [discountAmount]
      §e/evtintegration region <regionName/*> [discountAmount]
    permission: villagerenchanttracker.use

permissions:
  villagerenchanttracker.use:
    description: Allows use of basic plugin features
    default: true
  villagerenchanttracker.admin:
    description: Allows use of administrative commands
    default: op
    children:
      villagerenchanttracker.use: true